Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04" 

  config.vm.define "oelbouha" do |server|
    server.vm.hostname = "oelbouhaS"

    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "virtualbox" do |vb|
      vb.name = "oelbouha"
      vb.memory = 1024
      vb.cpus = 1
    end

    server.vm.provision "shell", path: "scripts/server.sh"
  end

  config.vm.define "oelbouha2" do |worker|
    worker.vm.hostname = "oelbouhaSW"

    worker.vm.network "private_network", ip: "192.168.56.111"

    worker.vm.provider "virtualbox" do |vb|
      vb.name = "oelbouha2"
      vb.memory = 1024
      vb.cpus = 1
    end

    worker.vm.provision "shell", path: "scripts/worker.sh"
  end
end